import { BaseEnvConfig } from '@app/my-library/env/enum/env.enum';

// put the env variables for the app here
export const ConfigEnum = {
  ...BaseEnvConfig,
  NODE_ENV: 'NODE_ENV',
  CLOUDINARY_API_KEY: 'CLOUDINARY_API_KEY',
  CLOUDINARY_API_SECRET: 'CLOUDINARY_API_SECRET',
  CLOUDINARY_NAME: 'CLOUDINARY_NAME',
  WALLET_SERVER_SECRET: 'WALLET_SERVER_SECRET',
  WALLET_SERVER: 'WALLET_SERVER',
  IDENTITYPASS_SEC_KEY: 'IDENTITYPASS_SEC_KEY',
  IDENTITYPASS_APP_ID: 'IDENTITYPASS_APP_ID',
  FRONTEND_URL: 'FRONTEND_URL',
  STRIPE_API_SECRET: 'STRIPE_API_SECRET',
  SERVER_URL: 'SERVER_URL',
  STRIPE_ACCOUNT: 'STRIPE_ACCOUNT',
  PATHWAY_SERVER: 'PATHWAY_SERVER',
  SENDGRID_API_KEY: 'SENDGRID_API_KEY',
  API_ENCRYPT_AND_DECRYPT_KEY: 'API_ENCRYPT_AND_DECRYPT_KEY',
  PROVIDUS_WEBHOOK_SECRET: 'PROVIDUS_WEBHOOK_SECRET',
};

export enum EnvNodeEnv {
  Local = 'local',
  Development = 'development',
  Production = 'production',
  Testing = 'testing',
}
