export enum AuthenticationEvent {
  SEND_REGISTRATION_CONFIRMAION_OTP = 'SEND_REGISTRATION_CONFIRMAION_OTP',
  SEND_2FA_VERIFICATION_CODE_1 = 'SEND_2FA_VERIFICATION_CODE_1',
  SEND_PASSWORD_RESET_MAIL = 'SEND_PASSWORD_RESET_MAIL',
  SEND_EMAIL_VEIRIFCATION_CODE_1 = 'SEND_EMAIL_VEIRIFCATION_CODE_1',
}
